spring.application.name=product-management
spring.datasource.url=jdbc:mysql://localhost:3306/sme_management_db
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
gemini.api.key=${GEMINI_API_KEY}
